# Generated by Django 4.1.5 on 2023-01-04 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('birthday', models.DateField(verbose_name='誕生日')),
                ('email_address', models.CharField(max_length=100)),
            ],
        ),
    ]
